using System.Net;
using System.Net.Mail;
using WeatherAlert.ML.Models;

namespace WeatherAlert.API.Services;

// Sends weather alert emails via Gmail SMTP using an App Password.
// No third party library needed — System.Net.Mail is built into .NET.
public class EmailAlertService(IConfiguration config, ILogger<EmailAlertService> logger)
{
    public async Task SendAlertAsync(
        string recipientEmail,
        string recipientName,
        List<AlertResult> alerts,
        string city,
        string state)
    {
        // Only send an email if at least one model flagged an alert
        var activeAlerts = alerts.Where(a => a.IsAlert).ToList();
        if (activeAlerts.Count == 0)
        {
            logger.LogInformation(
                "No active alerts for {Name} in {City} — email skipped",
                recipientName, city);
            return;
        }

        var subject = $"⚠️ Weather Alert for {city}, {state}";
        var body = BuildEmailBody(recipientName, city, state, alerts);

        await SendEmailAsync(recipientEmail, subject, body);
    }

    private async Task SendEmailAsync(string to, string subject, string body)
    {
        var smtpHost = config["Email:SmtpHost"]!;
        var smtpPort = int.Parse(config["Email:SmtpPort"]!);
        var senderEmail = config["Email:SenderEmail"]!;
        var appPassword = config["Email:AppPassword"]!;
        var senderName = config["Email:SenderName"]!;

        using var client = new SmtpClient(smtpHost, smtpPort)
        {
            EnableSsl = true,
            Credentials = new NetworkCredential(senderEmail, appPassword)
        };

        var message = new MailMessage
        {
            From = new MailAddress(senderEmail, senderName),
            Subject = subject,
            Body = body,
            IsBodyHtml = true
        };
        message.To.Add(to);

        await client.SendMailAsync(message);
        logger.LogInformation("Alert email sent to {Email}", to);
    }

    private static string BuildEmailBody(
        string name,
        string city,
        string state,
        List<AlertResult> alerts)
    {
        var alertRows = string.Join("", alerts.Select(a =>
        {
            var color = a.IsAlert ? "#d32f2f" : "#388e3c";
            var status = a.IsAlert ? "⚠️ ALERT" : "✅ Normal";

            return $"""
                <tr>
                    <td style='padding:8px;border:1px solid #ddd'>{a.AlertType}</td>
                    <td style='padding:8px;border:1px solid #ddd'>{a.ModelUsed}</td>
                    <td style='padding:8px;border:1px solid #ddd;color:{color};
                               font-weight:bold'>{status}</td>
                    <td style='padding:8px;border:1px solid #ddd'>{a.Confidence:P0}</td>
                    <td style='padding:8px;border:1px solid #ddd'>{a.Message}</td>
                </tr>
                """;
        }));

        return $"""
            <html>
            <body style='font-family:Arial,sans-serif;'>
                <h2 style='color:#1565c0'>🌩️ Weather Alert Report</h2>
                <p>Hello <strong>{name}</strong>,</p>
                <p>Here is your weather prediction report for
                   <strong>{city}, {state}</strong>:</p>
                <table style='border-collapse:collapse;width:100%'>
                    <thead>
                        <tr style='background:#1565c0;color:white'>
                            <th style='padding:8px'>Alert Type</th>
                            <th style='padding:8px'>ML Model</th>
                            <th style='padding:8px'>Status</th>
                            <th style='padding:8px'>Confidence</th>
                            <th style='padding:8px'>Details</th>
                        </tr>
                    </thead>
                    <tbody>{alertRows}</tbody>
                </table>
                <p style='margin-top:20px;color:#666;font-size:12px'>
                    Predictions generated by Decision Tree and Random Forest ML models
                    trained on Open-Meteo historical weather data.
                </p>
            </body>
            </html>
            """;
    }
}